---
default:
  image: ${CI_REGISTRY_IMAGE}
  interruptible: true

stages:
  - environment
  - build
  - quality gates
  - tests

include:
  - local: .gitlab/ci/environment.gitlab-ci.yml
  - local: .gitlab/ci/build.gitlab-ci.yml
  - local: .gitlab/ci/quality-gates.gitlab-ci.yml
  - local: .gitlab/ci/tests.gitlab-ci.yml
