.lint_template: &lint_definition
  stage: quality gates
  image: ${CI_REGISTRY_IMAGE}
  interruptible: true

clang-tidy:
  <<: *lint_definition
  script:
    - environment/scripts/clean_build_project.sh
    - environment/scripts/setup_compile_commands_database.sh
    - environment/scripts/clean_compile_commands_database.sh
    - run-clang-tidy -p=build

clang-format:
  <<: *lint_definition
  script:
    - find . -name '*.hpp' -or -name '*.cpp' | xargs clang-format --dry-run

cppcheck:
  <<: *lint_definition
  script:
    - cppcheck --force --enable=all .

valgrind:
  <<: *lint_definition
  script:
    - valgrind --leak-check=yes build/bin/leetcode-solutions
