.lint_template: &lint_definition
  stage: quality gates
  image: ${CI_REGISTRY_IMAGE}
  interruptible: true

clang-tidy:
  <<: *lint_definition
  script:
    - environment/clean_build_project.sh
    - run-clang-tidy -p=build

clang-format:
  <<: *lint_definition
  script:
    - find . -name '*.hpp' -or -name '*.cpp' | xargs clang-format --dry-run --verbose

cppcheck:
  <<: *lint_definition
  script:
    - cppcheck --force --enable=all .

valgrind:
  <<: *lint_definition
  script:
    - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose ./build/bin/leetcode-solutions-tests
