build:
  stage: build
  image: ${CI_REGISTRY_IMAGE}
  before_script:
    - ccache --set-config=cache_dir=$(pwd)/.ccache
  script:
    - environment/clean_build_project.sh
    - ls -la build
  artifacts:
    name: leetcode-solutions-tests
    paths:
      - build
  cache:
    key: "${CI_JOB_NAME}-${CI_COMMIT_BRANCH}"
    paths:
      - .ccache
  interruptible: true
