clang-tidy:
  stage: quality gates
  extends: .cache-ccache
  dependencies: [ ]
  variables:
    CODACY_URL: https://api.codacy.com
    CODACY_CLANG_TIDY_VERSION: 1.2.1
  script:
    - environment/clean_build_project.sh
    - wget --continue https://github.com/codacy/codacy-clang-tidy/releases/download/${CODACY_CLANG_TIDY_VERSION}/codacy-clang-tidy-${CODACY_CLANG_TIDY_VERSION}
    - chmod +x codacy-clang-tidy-${CODACY_CLANG_TIDY_VERSION}
    - run-clang-tidy -p=build | ./.gitlab/scripts/codacy_send_results.sh

clang-format:
  stage: quality gates
  dependencies: [ ]
  script:
    - find . -name '*.cpp' | xargs clang-format --dry-run --verbose

lcov:
  stage: quality gates
  extends: .cache-ccache
  dependencies: [ ]
  script:
    - export CXXFLAGS="-g -O0 --coverage"
    - environment/clean_build_project.sh
    - build/bin/leetcode-solutions-tests
    - lcov --no-external --capture --directory=. --output-file=${CI_JOB_NAME}.info
    - bash <(curl -Ls https://coverage.codacy.com/get.sh) report --coverage-reports ${CI_JOB_NAME}.info
    - genhtml ${CI_JOB_NAME}.info --output-directory ${CI_JOB_NAME}-output
  artifacts:
    name: ${CI_JOB_NAME}
    paths:
      - ${CI_JOB_NAME}-output

valgrind:
  stage: quality gates
  script:
    - valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose build/bin/leetcode-solutions-tests
