tests:
  stage: tests
  script:
    - build/bin/leetcode-solutions-tests --reporter=junit --out=${CI_JOB_NAME}-report.xml
  artifacts:
    when: always
    reports:
      junit: ${CI_JOB_NAME}-report.xml
